#!/usr/bin/env python3
"""
Train LoRA Rank-16 adapter on the Alexandria-MP-20 dataset.

Hyperparameters
---------------
  rank        : 8
  alpha       : 16  (scaling = alpha / rank = 2)
  lr          : 5e-5
  optimizer   : Adam (β₁=0.9, β₂=0.999)
  scheduler   : ReduceLROnPlateau (factor 0.5, patience 20)
  batch size  : 64 structures / GPU
  weight decay: 0.01
  grad clip   : value-based ±0.5
  epochs      : 200 (with early stopping)
  conditioning: energy_above_hull = 0.0 eV/atom

Usage
-----
  python training/train_rank16.py \
      --generator_path /path/to/installed/generator \
      --dataset_path   /path/to/alex_mp_20 \
      --output_dir     checkpoints/lora_rank16
"""

import argparse
import logging
import os
import subprocess
import sys
import textwrap
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

RANK = 16
ALPHA = 32.0
LORA_DROPOUT = 0.1
LEARNING_RATE = 5e-5
WEIGHT_DECAY = 0.01
BATCH_SIZE = 64
MAX_EPOCHS = 200
GRAD_CLIP_VAL = 0.5
LR_PATIENCE = 20
LR_FACTOR = 0.5


def build_config(generator_path: Path, dataset_path: Path, output_dir: Path) -> Path:
    """Write the Hydra YAML config for Rank-16 training and return its path."""
    config_content = textwrap.dedent(f"""\
        # LoRA Rank-16 training configuration
        # Auto-generated by training/train_rank16.py

        defaults:
          - base_config
          - _self_

        model:
          _target_: mattergen.adapter_lora.GemNetTLoRAAdapter
          lora_rank: {RANK}
          lora_alpha: {ALPHA}
          lora_dropout: {LORA_DROPOUT}
          property_embeddings_adapt:
            energy_above_hull:
              _target_: mattergen.property_embeddings.ScalarEmbedding
              embedding_dim: 512

        training:
          optimizer:
            _target_: torch.optim.Adam
            lr: {LEARNING_RATE}
            betas: [0.9, 0.999]
            weight_decay: {WEIGHT_DECAY}
          scheduler:
            _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
            factor: {LR_FACTOR}
            patience: {LR_PATIENCE}
            mode: min
          gradient_clip_algorithm: value
          gradient_clip_val: {GRAD_CLIP_VAL}
          max_epochs: {MAX_EPOCHS}
          batch_size: {BATCH_SIZE}
          early_stopping:
            monitor: val/loss
            patience: 30
            mode: min

        data:
          dataset_path: {dataset_path}
          conditioning_properties:
            - energy_above_hull

        callbacks:
          model_checkpoint:
            dirpath: {output_dir}/checkpoints
            filename: "lora_rank{RANK}_epoch{{epoch:03d}}_val{{val/loss:.4f}}"
            monitor: val/loss
            mode: min
            save_top_k: 3
            save_last: true

        trainer:
          accelerator: gpu
          devices: 1
          precision: 16
          log_every_n_steps: 50

        hydra:
          run:
            dir: {output_dir}
    """)

    config_path = output_dir / "config_rank16.yaml"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(config_content)
    logger.info(f"Config written to {config_path}")
    return config_path


def train(generator_path: Path, dataset_path: Path, output_dir: Path) -> None:
    """Launch the training process."""
    config_path = build_config(generator_path, dataset_path, output_dir)

    cmd = [
        sys.executable, "-m", "mattergen.run_training",
        f"--config-path={config_path.parent}",
        f"--config-name={config_path.stem}",
        f"data.dataset_path={dataset_path}",
        f"hydra.run.dir={output_dir}",
    ]

    logger.info("Starting LoRA Rank-16 training ...")
    logger.info("Command: " + " ".join(cmd))

    env = os.environ.copy()
    env["PYTHONPATH"] = str(generator_path) + os.pathsep + env.get("PYTHONPATH", "")

    result = subprocess.run(cmd, env=env, cwd=str(generator_path))
    if result.returncode != 0:
        logger.error(f"Training failed with return code {result.returncode}")
        sys.exit(result.returncode)

    logger.info(f"Training complete. Checkpoints saved to {output_dir}/checkpoints/")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train LoRA Rank-16 adapter for crystal structure generation.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--generator_path", type=Path, required=True,
        help="Path to the installed base generator package root.",
    )
    parser.add_argument(
        "--dataset_path", type=Path, required=True,
        help="Path to the Alexandria-MP-20 dataset directory.",
    )
    parser.add_argument(
        "--output_dir", type=Path, default=Path("checkpoints/lora_rank16"),
        help="Directory for checkpoints and logs.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    train(
        generator_path=args.generator_path,
        dataset_path=args.dataset_path,
        output_dir=args.output_dir,
    )
